version: "3"
services:
  morning:
    image: ${TEST_IMAGE}
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/ping"]
      interval: 5s
      timeout: 5s
      retries: 12
    environment:
      - USER_UID=1000
      - USER_GID=1000
      - LOGIN_USER=fake
      - LOGIN_PASSWORD=password
    restart: always
    expose:
      - '5000'
    depends_on:
      - redis
      - selenium
  redis:
    restart: always
    image: "redis:alpine"
    expose:
      - '6379'
    volumes:
      - redis-data:/var/lib/redis
    environment:
      - REDIS_REPLICATION_MODE=master
    healthcheck:
      test: [ "CMD-SHELL", "redis-cli", "ping" ]
      interval: 5s
      timeout: 5s
      retries: 12
  selenium:
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:4444/wd/hub/status"]
      interval: 5s
      timeout: 5s
      retries: 12
    shm_size: '2gb'
    image: selenium/standalone-chrome
    environment:
      - USER_UID=1000
      - USER_GID=1000
      - SE_NODE_MAX_SESSIONS=100
      - VNC_NO_PASSWORD=1
    restart: always
    expose:
      - '4444'
volumes:
  redis-data: