apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: selenium
  name: selenium
spec:
  ports:
    - name: "4444"
      port: 4444
      targetPort: 4444
  selector:
    io.kompose.service: selenium
status:
  loadBalancer: {}
