name: main

on:
  push:
    tags:
      - "v*"
    branches:
      - main
      - "fix-*"
      - "feature-"

jobs:
  cancel-previous-runs:
    runs-on: ubuntu-latest
    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.9.1
        with:
          access_token: ${{ github.token }}

  python-lint:
    runs-on: ubuntu-latest
    name: CI workflow
    steps:
      - name: checkout source repo
        uses: actions/checkout@v2
      # - name: Install libraries!
      #   run: |
      #     pip install --upgrade pip
      #     pip install types-redis types-requests
      #     pip install -r requirements.txt
      - name: linting
        uses: alexanderdamiani/pylinter@v1.4.0
        with:
          python-root: "./src/"
          flake8-flags: "--count --show-source --statistics"
          mypy-flags: "--ignore-missing-imports --non-interactive --install-types"
          fail-on-isort: true

  build:
    needs:
      - python-lint
    runs-on: ubuntu-latest
    steps:
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}dc log
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Do Checkout
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
        with:
          config: .github/config/buildkitd.toml
          install: true

      - name: Docker Build
        run: |
          docker info
          docker buildx version
          .github/bin/docker-build.sh
        env:
          DOCKER_CLI_EXPERIMENTAL: enabled
          DOCKER_BUILD_PLATFORM: linux/amd64,linux/arm64,linux/arm/v7
          REPOSITORY: ${{ github.repository }}
