name: main

on:
  push:
    tags:
      - "v*"
    branches:
      - main
      - "fix-*"
      - "feature-"

jobs:
  cancel-previous-runs:
    name: Cancel previous runs
    runs-on: ubuntu-latest
    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.9.1
        with:
          access_token: ${{ github.token }}

  python-lint:
    runs-on: ubuntu-latest
    name: Check Code quality
    steps:
      - name: checkout source repo
        uses: actions/checkout@v2

      - name: linting
        uses: alexanderdamiani/pylinter@v1.4.0
        with:
          python-root: "./src/"
          flake8-flags: "--count --show-source --statistics --max-line-length=160"
          mypy-flags: "--ignore-missing-imports --non-interactive --install-types"
          fail-on-isort: true

  build:
    name: Build the containers
    needs:
      - python-lint
    runs-on: ubuntu-latest
    steps:

      - name: Do Checkout
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
        with:
          config: .github/config/buildkitd.toml
          install: true

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: "ghcr.io/${{ github.repository }}:latest,ghcr.io/${{ github.repository }}:${{ github.tag }},ghcr.io/${{ github.repository }}:${{ github.branch }}"
          cache-from: type=registry,ref=ghcr.io/${{ github.repository }}:buildcache
          cache-to: type=registry,ref=ghcr.io/${{ github.repository }}:buildcache,mode=max
          platforms: linux/amd64,linux/arm64,linux/arm/v7
      - name: Move cache
        run: |
          rm -rf /tmp/.buildx-cache
          mv /tmp/.buildx-cache-new /tmp/.buildx-cache
      # - name: Docker Build
      #   run: |
      #     .github/bin/docker-push.sh
      #   env:
      #     DOCKER_CLI_EXPERIMENTAL: enabled
      #     DOCKER_BUILD_PLATFORM: linux/amd64,linux/arm64,linux/arm/v7
      #     REPOSITORY: ${{ github.repository }}
